"""
Self-Verification Checker
==========================

Validates generated recommendation reasons for compliance and factuality
before they reach end-users.

Three verification stages:
    1. **Rule-based compliance** -- pattern matching against configurable
       prohibited-pattern lists.
    2. **Prompt injection detection** -- configurable regex patterns that
       detect injection attacks in both generated text and user inputs.
    3. **LLM factuality check** (optional) -- calls an
       :class:`AbstractLLMProvider` to cross-reference the reason against
       the source context.

All patterns and thresholds come from **config YAML**.

Config example (``reason.self_checker``)::

    reason:
      self_checker:
        compliance_rules:
          guaranteed_return:
            pattern: "guaranteed\\\\s+return"
            severity: critical
            description: "Must not promise guaranteed returns."
          loss_impossible:
            pattern: "no\\\\s+loss|loss\\\\s+impossible"
            severity: critical
            description: "Must not claim loss is impossible."
        injection_patterns:
          - "ignore\\\\s+(previous|all|above)\\\\s+(instructions?|prompts?|rules?)"
          - "<\\\\s*/?\\\\s*system\\\\s*>"
          - "you\\\\s+are\\\\s+now\\\\s+(a|an|the)"
          - "system\\\\s*:\\\\s*"
        ai_disclosure: >
          This recommendation was generated by an AI system.
          The final decision rests with you.
        ai_opt_out: >
          If you prefer not to receive AI-generated recommendations,
          please contact support.
        factuality_threshold: 0.8
        enable_llm_check: false
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

__all__ = ["SelfChecker", "CheckResult"]


@dataclass
class CheckResult:
    """Outcome of the self-verification pipeline.

    Attributes:
        verdict: ``"pass"`` / ``"revise"`` / ``"reject"``.
        compliance_passed: Whether all compliance rules passed.
        injection_safe: Whether no injection patterns were detected.
        factuality_score: LLM-assessed factuality (0-1), or 1.0 if
                          LLM check was skipped.
        violations: List of rule names that failed.
        injection_matches: List of matched injection patterns.
        feedback: Human-readable summary of issues.
        ai_disclosure: AI disclosure text to attach.
        ai_opt_out: Opt-out instructions to attach.
    """

    verdict: str
    compliance_passed: bool
    injection_safe: bool
    factuality_score: float
    violations: List[str] = field(default_factory=list)
    injection_matches: List[str] = field(default_factory=list)
    feedback: str = ""
    ai_disclosure: str = ""
    ai_opt_out: str = ""


class SelfChecker:
    """Rule-based compliance + optional LLM factuality checker.

    Args:
        config: Full pipeline config.  Reads ``config["reason"]["self_checker"]``.
        llm_provider: Optional :class:`AbstractLLMProvider` instance.
                      Required only if ``enable_llm_check`` is True.
    """

    def __init__(
        self,
        config: Dict[str, Any],
        llm_provider: Optional[Any] = None,
    ) -> None:
        sc_cfg = config.get("reason", {}).get("self_checker", {})

        # Compliance rules
        self.compliance_rules: Dict[str, Dict[str, Any]] = sc_cfg.get(
            "compliance_rules", {},
        )
        self._compiled_rules: Dict[str, re.Pattern] = {}
        for name, rule in self.compliance_rules.items():
            try:
                self._compiled_rules[name] = re.compile(
                    rule["pattern"], re.IGNORECASE,
                )
            except re.error as exc:
                logger.warning(
                    "SelfChecker: invalid regex for rule '%s': %s", name, exc,
                )

        # Injection patterns
        raw_patterns: List[str] = sc_cfg.get("injection_patterns", [])
        self._injection_compiled: List[tuple[str, re.Pattern]] = []
        for p in raw_patterns:
            try:
                self._injection_compiled.append((p, re.compile(p, re.IGNORECASE)))
            except re.error as exc:
                logger.warning(
                    "SelfChecker: invalid injection regex '%s': %s", p, exc,
                )

        # AI disclosure texts
        self.ai_disclosure: str = sc_cfg.get(
            "ai_disclosure",
            "This recommendation was generated by an AI system.",
        )
        self.ai_opt_out: str = sc_cfg.get(
            "ai_opt_out",
            "Contact support to opt out of AI recommendations.",
        )

        # LLM factuality
        self.enable_llm_check: bool = sc_cfg.get("enable_llm_check", False)
        self.factuality_threshold: float = sc_cfg.get("factuality_threshold", 0.8)
        self.llm_provider = llm_provider

        logger.info(
            "SelfChecker initialised: %d compliance rules, %d injection patterns, "
            "llm_check=%s",
            len(self._compiled_rules),
            len(self._injection_compiled),
            self.enable_llm_check,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def check(
        self,
        reason_text: str,
        source_context: Optional[Dict[str, Any]] = None,
    ) -> CheckResult:
        """Run full verification pipeline on a reason string.

        Args:
            reason_text: The generated recommendation reason text.
            source_context: Optional ground-truth context for LLM
                            factuality checking.

        Returns:
            A :class:`CheckResult`.
        """
        # Stage 1: compliance
        compliance_passed, violations, violation_details = self._check_compliance(
            reason_text,
        )

        # Stage 2: injection detection
        injection_safe, injection_matches = self._check_injection(reason_text)

        # Stage 3: LLM factuality (optional)
        factuality_score = 1.0
        llm_feedback = ""
        if self.enable_llm_check and self.llm_provider is not None and source_context:
            factuality_score, llm_feedback = self._check_factuality(
                reason_text, source_context,
            )

        # Verdict
        verdict = self._determine_verdict(
            compliance_passed,
            injection_safe,
            factuality_score,
            violation_details,
        )

        # Build feedback summary
        feedback_parts: List[str] = []
        if violations:
            feedback_parts.append(
                "Compliance violations: " + ", ".join(violations),
            )
        if injection_matches:
            feedback_parts.append(
                f"Injection patterns detected: {len(injection_matches)}",
            )
        if llm_feedback:
            feedback_parts.append(f"LLM feedback: {llm_feedback}")

        return CheckResult(
            verdict=verdict,
            compliance_passed=compliance_passed,
            injection_safe=injection_safe,
            factuality_score=factuality_score,
            violations=violations,
            injection_matches=injection_matches,
            feedback=" | ".join(feedback_parts) if feedback_parts else "All checks passed.",
            ai_disclosure=self.ai_disclosure,
            ai_opt_out=self.ai_opt_out,
        )

    # ------------------------------------------------------------------
    # Stage 1: Compliance
    # ------------------------------------------------------------------

    def _check_compliance(
        self,
        text: str,
    ) -> tuple[bool, List[str], List[Dict[str, Any]]]:
        """Check text against compliance rules.

        Returns:
            (all_passed, violation_names, violation_details)
        """
        violations: List[str] = []
        details: List[Dict[str, Any]] = []

        for name, compiled in self._compiled_rules.items():
            match = compiled.search(text)
            if match:
                rule_cfg = self.compliance_rules[name]
                violations.append(name)
                details.append({
                    "rule": name,
                    "severity": rule_cfg.get("severity", "medium"),
                    "description": rule_cfg.get("description", ""),
                    "matched_text": match.group(0),
                })

        # Critical violations cause failure
        has_critical = any(
            d["severity"] == "critical" for d in details
        )
        return not has_critical, violations, details

    # ------------------------------------------------------------------
    # Stage 2: Injection
    # ------------------------------------------------------------------

    def _check_injection(
        self,
        text: str,
    ) -> tuple[bool, List[str]]:
        """Check text for prompt injection patterns.

        Returns:
            (is_safe, matched_pattern_strings)
        """
        matches: List[str] = []
        for raw, compiled in self._injection_compiled:
            if compiled.search(text):
                matches.append(raw)
        return len(matches) == 0, matches

    # ------------------------------------------------------------------
    # Stage 3: LLM factuality
    # ------------------------------------------------------------------

    def _check_factuality(
        self,
        reason_text: str,
        source_context: Dict[str, Any],
    ) -> tuple[float, str]:
        """Use LLM to assess factual grounding of the reason.

        Returns:
            (factuality_score, feedback_text)
        """
        context_str = json.dumps(source_context, default=str, ensure_ascii=False)

        prompt = (
            "You are a factuality auditor. Given the SOURCE CONTEXT and the "
            "GENERATED REASON below, assess whether the reason is factually "
            "grounded in the context.\n\n"
            f"## Source Context\n{context_str[:2000]}\n\n"
            f"## Generated Reason\n{reason_text}\n\n"
            "Respond in JSON:\n"
            '{"factual_score": 0.0, "feedback": "..."}\n'
            "factual_score is 0.0 to 1.0 (1.0 = fully grounded)."
        )

        try:
            response = self.llm_provider.generate(prompt)
            return self._parse_factuality_response(response)
        except Exception as exc:
            logger.error("LLM factuality check failed: %s", exc)
            return 0.5, f"LLM check error: {exc}"

    @staticmethod
    def _parse_factuality_response(response: str) -> tuple[float, str]:
        """Extract score and feedback from LLM JSON response."""
        json_match = re.search(r"\{.*\}", response, re.DOTALL)
        if not json_match:
            return 0.5, "Failed to parse LLM response."
        try:
            data = json.loads(json_match.group(0))
            score = float(max(0.0, min(1.0, data.get("factual_score", 0.5))))
            feedback = data.get("feedback", "")
            return score, feedback
        except (json.JSONDecodeError, TypeError, ValueError):
            return 0.5, "JSON decode error in LLM response."

    # ------------------------------------------------------------------
    # Verdict logic
    # ------------------------------------------------------------------

    def _determine_verdict(
        self,
        compliance_passed: bool,
        injection_safe: bool,
        factuality_score: float,
        violation_details: List[Dict[str, Any]],
    ) -> str:
        """Produce a final verdict string."""
        # Immediate reject on critical compliance or injection
        if not compliance_passed or not injection_safe:
            return "reject"

        # Factuality check
        if factuality_score >= self.factuality_threshold:
            # Check for non-critical warnings
            has_warnings = any(
                d["severity"] in ("medium", "high") for d in violation_details
            )
            return "revise" if has_warnings else "pass"

        if factuality_score >= 0.5:
            return "revise"

        return "reject"
